---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: kafka-monitor
    metrics: kafka-monitor
  name: kafka-monitor
spec:
  namespaceSelector:
    matchNames:
    - kafka-monitor
  selector:
    matchLabels:
      app: kafka-monitor
  endpoints:
  - port: http
    path: /actuator/prometheus
